things/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    url(r'^join/$', views.register, name='join'),
    url(r'^profile/(?P<slug>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^settings/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.SettingsUpdateView.as_view(), name='edit_settings'),

    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^user/(?P<user_slug>[\w-]+)/$', views.user_profile, name='user'),

    url(r'^actors/$', views.ActorListView.as_view(), name='actors'),
    url(r'^actors/(?P<slug>[\w-]+)/$', views.ActorListView.as_view(), name='search_actors'),
    url(r'^add-actor/$', views.ActorCreateView.as_view(),name='new_actor'),
    url(r'^actor/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.ActorUpdateView.as_view(), name='edit_actor'),
    url(r'^actor/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.ActorDeleteView.as_view(),name='del_actor'),
    url(r'^actor/(?P<slug>[\w-]+)/$', views.ActorDetailView.as_view(), name='actor'),

    url(r'^vehicles/$', views.VehicleListView.as_view(), name='vehicles'),
    url(r'^add-vehicle/$', views.VehicleCreateView.as_view(),name='new_vehicle'),
    url(r'^vehicle/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.VehicleUpdateView.as_view(), name='edit_vehicle'),
    url(r'^vehicle/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.VehicleDeleteView.as_view(),name='del_vehicle'),
    url(r'^vehicle/(?P<slug>[\w-]+)/$', views.VehicleDetailView.as_view(), name='vehicle'),

    url(r'^musicians/$', views.MusicianListView.as_view(), name='musicians'),
    url(r'^add-musician/$', views.MusicianCreateView.as_view(),name='new_musician'),
    url(r'^musician/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.MusicianUpdateView.as_view(), name='edit_musician'),
    url(r'^musician/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.MusicianDeleteView.as_view(),name='del_musician'),
    url(r'^musician/(?P<slug>[\w-]+)/$', views.MusicianDetailView.as_view(), name='musician'),

    url(r'^movies/$', views.MovieListView.as_view(), name='movies'),
    url(r'^add-movie/$', views.MovieCreateView.as_view(),name='new_movie'),
    url(r'^movie/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.MovieUpdateView.as_view(), name='edit_movie'),
    url(r'^movie/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.MovieDeleteView.as_view(),name='del_movie'),
    url(r'^movie/(?P<slug>[\w-]+)/$', views.MovieDetailView.as_view(), name='movie'),

    url(r'^tvshows/$', views.TVShowListView.as_view(), name='tvshows'),
    url(r'^add-tvshow/$', views.TVShowCreateView.as_view(),name='new_tvshow'),
    url(r'^tvshow/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.TVShowUpdateView.as_view(), name='edit_tvshow'),
    url(r'^tvshow/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.TVShowDeleteView.as_view(),name='del_tvshow'),
    url(r'^tvshow/(?P<slug>[\w-]+)/$', views.TVShowDetailView.as_view(), name='tvshow'),

    url(r'^animes/$', views.AnimeListView.as_view(), name='animes'),
    url(r'^add-anime/$', views.AnimeCreateView.as_view(),name='new_anime'),
    url(r'^anime/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.AnimeUpdateView.as_view(), name='edit_anime'),
    url(r'^anime/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.AnimeDeleteView.as_view(),name='del_anime'),
    url(r'^anime/(?P<slug>[\w-]+)/$', views.AnimeDetailView.as_view(), name='anime'),

    url(r'^songs/$', views.SongListView.as_view(), name='songs'),
    url(r'^add-song/$', views.SongCreateView.as_view(),name='new_song'),
    url(r'^song/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.SongUpdateView.as_view(), name='edit_song'),
    url(r'^song/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.SongDeleteView.as_view(),name='del_song'),
    url(r'^song/(?P<slug>[\w-]+)/$', views.SongDetailView.as_view(), name='song'),

    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^add-book/$', views.BookCreateView.as_view(),name='new_book'),
    url(r'^book/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.BookUpdateView.as_view(), name='edit_book'),
    url(r'^book/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.BookDeleteView.as_view(),name='del_book'),
    url(r'^book/(?P<slug>[\w-]+)/$', views.BookDetailView.as_view(), name='book'),
]

til/urls.py
from django.conf.urls import  include, url
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('things.urls', namespace="things")),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

things/models.py
import os

from django.db import models
from django.db.models import F
from django.db.models.signals import pre_save, post_save
from django.conf import settings
from django.contrib.auth.models import User as UserModel
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django_countries.fields import CountryField

from .utils import *

User = settings.AUTH_USER_MODEL

class Profile(models.Model):
    owner           =models.ForeignKey(User)
    first_name      =models.CharField(max_length=50, blank=True, null=True,validators=[alphanumspacedash])
    last_name       =models.CharField(max_length=50, blank=True, null=True, validators=[alphanumspacedash])
    dob             =models.DateField(blank=True, null=True)
    location        =models.CharField(null=True, blank=True, max_length = 50)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
        
    def __str__(self):
        return self.owner.username
    
    def get_absolute_url(self):
        return reverse('things:profile', kwargs={'slug':self.slug})

    def get_initials(self):
        initial =''
        if not (self.first_name and self.last_name):
            initial=self.owner.username[0]
        else:
            if self.first_name:
                initial+=self.first_name[0]
            if self.last_name:
                initial+=self.last_name[0]
        return initial

    class Meta:
        ordering = ('owner','timestamp',)

    @property
    def title(self):
        return self.owner.username

class Settings(models.Model):
    owner = models.ForeignKey(User)
    show_actors =models.BooleanField(default=False)
    show_directors =models.BooleanField(default=False)
    show_writers =models.BooleanField(default=False)
    show_artists =models.BooleanField(default=False)
    show_musicians =models.BooleanField(default=False)
    show_dancers =models.BooleanField(default=False)
    show_sportspersons =models.BooleanField(default=False)
    show_fitnesspersons =models.BooleanField(default=False)
    show_femalemodels =models.BooleanField(default=False)
    show_songs =models.BooleanField(default=False)
    show_movies =models.BooleanField(default=False)
    show_tvshows =models.BooleanField(default=False)
    show_animes =models.BooleanField(default=False)
    show_books =models.BooleanField(default=False)
    show_foods =models.BooleanField(default=False)
    show_youtubechannels =models.BooleanField(default=False)
    show_websites =models.BooleanField(default=False)
    show_apps =models.BooleanField(default=False)
    show_videogames =models.BooleanField(default=False)
    show_cars=models.BooleanField(default=False)
    show_bikes =models.BooleanField(default=False)
    show_adultmodels =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
        
    def __str__(self):
        return self.owner.username
    
    def get_absolute_url(self):
        return reverse('things:profile', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('owner','timestamp',)
        verbose_name_plural = "settings"

    @property
    def title(self):
        return self.owner.username


def user_registration_receiver(sender, instance, *args, **kwargs):
    if not Profile.objects.filter(owner=instance):
        newpro=Profile.objects.create(owner=instance)
        newpro.slug=instance.username
        newpro.save()
    if not Settings.objects.filter(owner=instance):
        newset=Settings.objects.create(owner=instance)
        newset.slug=instance.username
        newset.save()

post_save.connect(user_registration_receiver, sender=UserModel)

class Actor(models.Model):
    genders = (
		('f', 'Female'),
        ('m', 'Male'),
        ('o', 'Not Specified'),
    )
    def update_image_file(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (instance.slug, ext)
        return os.path.join('actors', filename)

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedash])
    gender          =models.CharField(choices=genders, blank=False, max_length=12, default='o')
    country         =CountryField(blank_label='(select country)')
    dob             =models.DateField(blank=False, default='01/01/89')
    image           =models.ImageField(upload_to=update_image_file, blank=True, null=True)
    insta           =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('things:actor', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name')
        unique_together = ('owner', 'rank', 'gender')

    @property
    def is_female(self):
        if self.gender == 'f':
            return True
        else:
            return False

    @property
    def title(self):
        return self.name


class Director(models.Model):    
    def update_image_file(instance, filename):
        pass

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedash])
    country         =CountryField(blank_label='(select country)')
    is_active	    =models.BooleanField(default=True)
    image_url        =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('things:director', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name',)
        unique_together = ('owner', 'rank')

    @property
    def title(self):
        return self.name


class Writer(models.Model):
    genders = (
		('f', 'Female'),
        ('m', 'Male'),
    )
    def update_image_file(instance, filename):
        pass

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedashq])
    gender          =models.CharField(choices=genders, blank=False, max_length=20)
    genres          =models.CharField(blank=False, max_length=80)
    languages       =models.CharField(blank=False, max_length=80)
    country         =CountryField(blank_label='(select country)')
    is_active	    =models.BooleanField(default=True)
    image_url        =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('things:writer', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name',)
        unique_together = ('owner', 'rank')

    @property
    def title(self):
        return self.name


class Artist(models.Model):
    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedashq])
    country         =CountryField(blank_label='(select country)')
    genres          =models.CharField(blank=False, max_length=80)
    is_active	    =models.BooleanField(default=True)
    image_url       =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('things:artist', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name',)
        unique_together = ('owner', 'rank')

    @property
    def title(self):
        return self.name


class Musician(models.Model):
    mtypes = (
		('fs', 'Female Singer'),
        ('ms', 'Male Singer'),
        ('bs', 'Band/Duo/Group'),
    )
    def update_image_file(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (instance.slug, ext)
        return os.path.join('musicians', filename)

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedashq])
    mtype           =models.CharField(choices=mtypes, blank=False, max_length=20)
    country         =CountryField(blank_label='(select country)')
    languages       =models.CharField(blank=False, max_length=80)

things/templates/things/actor_detail.html
{%extends "base.html"%}
{%load static%}
{% block title %}{{object.name}} | {{block.super}} {% endblock %}

{%block metatag%}
    <meta name="twitter:title" content="{{object.name}}" />
    <meta property="og:title" content="{{object.name}}" />
    <meta name="description" content="{{object.name}}"/>
    <meta name="twitter:description" content="{{object.remarks}}" />
    <meta property="og:description" content="{{object.remarks}}" />
    <meta property="og:url" content="{{object.get_absolute_url}}" />
    <meta name="twitter:domain" content="{{object.get_absolute_url}}" />
    <link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}">
{%endblock metatag%}

{%block precontent%}
<div id="generic_hero_img">
    <div id="generic_heading">{{object.name}}</div>
</div>
{%endblock precontent%}

{%block content%}
<div class="col-xs-12">
    <div class="col-xs-12 col-md-3">
        {%if request.user == object.owner%}
        {%if object.rank%}
        <div id="generic_rank">
            <i class="fa fa-bolt" aria-hidden="true"></i>{{object.get_rank_display}} 
        </div>
        {%endif%}
        {%endif%}
        <div id="generic_info">
            <h3 class="generic_card_info1">{%if object.dob%}<i class="fa fa-birthday-cake" aria-hidden="true"></i> {{object.dob}}{%endif%}</h3>
            <br>
            <p class="generic_country"><i class="flag2x {{ object.country.flag_css }}"></i><span>{{object.get_country_display}}</span></p>
            <p><a href="{%if object.insta%}{{object.insta}}{%endif%}" target='_blank'>{%if object.insta%}{{object.insta}}{%endif%}</a></p>
            {%if object.remarks%}
            <h3><sup><i class="fa fa-quote-left" aria-hidden="true"></i></sup> {{object.remarks}} <sup><i class="fa fa-quote-right" aria-hidden="true"></i></sup></h3>
            {%endif%}
            <p>{%if object.is_private%}<span id="private">This is kept private</span>{%endif%}</p>
        </div>
        <div id="generic_extra" class="col-xs-12 ">
            {%if request.user == object.owner%}
            <div id="generic_buttons">
                <button class="generic_edit">
                    <a href='{% url "things:edit_actor" object.id object.slug %}'><i class="fa fa-edit" aria-hidden="true"></i> Edit this page</a>
                </button>
                <button class="generic_edit">
                    <a href='{% url "things:del_actor" object.id object.slug %}'><i class="fa fa-trash" aria-hidden="true"></i> Delete this page</a>
                </button>
            </div>
            {%else%}
            <div class="generic_creator">
                <h5>Created by <a href="{%url 'things:user' object.owner%}">{{object.owner}}</a> at <i class="fa fa-clock" aria-hidden="true"></i> {{object.timestamp}}</h5>
            </div>
            {%endif%}
        </div>
    </div>

    <div class="col-xs-12 col-md-9" id="generic_img">
        <img src="{{object.image.url}}" alt="{{object.name}}">
        <p id='generic_img_link'><a href="{{object.image.url}}" target='_blank'><i class="fa fa-picture-o" aria-hidden="true"></i> To view the full image, click here</a></p>
    </div>
</div>

<div class="generic_subset_section col-xs-12">
    <div id="generic_subset_movie" class="col-xs-12">
        {%if object.movie_set.all.count == 0%}
        <div class="col-xs-12" id="generic_empty">
            <img src="/media/empty.png" alt="Ain't nothing in here." width="100%">
            <h2>No Movies of this actor</h2>
            {%if request.user == object.owner%}
            <h3><a class='add_more' href="{%url 'things:new_movie'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create a movie</a></h3>
            {%endif%} 
        </div>
        {%else%}
            <div class="col-xs-12">
                <h2><i class="fa fa-film" aria-hidden="true"></i> Movies where {{object.name}} appears in</h2>
            </div>
        {%endif%}    
        {% for movie in object.movie_set.all %}
        <a class="generic_subset_link" href={{movie.get_absolute_url}}>
            <div class="col-xs-12">
                <h3>{{movie.name}} ({{movie.year}})</h3>
            </div>
        </a>
        {%endfor%}
    </div>

    <div id="generic_subset_tv" class="col-xs-12">
        {%if object.tvshow_set.all.count == 0%}
        <div class="col-xs-12" id="generic_empty">
            <img src="/media/empty.png" alt="Ain't nothing in here." width="100%">
            <h2>No TV Show of this actor</h2>
            {%if request.user == object.owner%}
            <h3><a class='add_more' href="{%url 'things:new_tvshow'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create a TV Show</a></h3>
            {%endif%}
        </div>
        {%else%}
            <div class="col-xs-12">
                <h2><i class="fa fa-tv" aria-hidden="true"></i> TV Shows where {{object.name}} appears in</h2>
            </div>
        {%endif%}
        {% for tvshow in object.tvshow_set.all %}
        <a class="generic_subset_link" href={{tvshow.get_absolute_url}}>
            <div class="col-xs-12">
                <h3>{{tvshow.name}} ({{tvshow.started_from}})</h3>
            </div>
        </a>
        {%endfor%}
    </div>
</div>
{%endblock content%}

things/templates/things/home.html
{%extends "base.html"%}
{%load static%}
{% block title %}Home | {{block.super}} {% endblock %}

{%block metatag%}
    <meta property="og:title" content="Home Page" />
    <meta name="twitter:title" content="Home Page" />
    <meta name="description" content="Home Page"/>
    <meta name="twitter:description" content="Home Page" />
    <meta property="og:description" content="Home Page" />
    <meta property="og:url" content="likelist.pythonanywhere.com/" />
    <meta name="twitter:domain" content="likelist.pythonanywhere.com/" />
    <meta name="keywords" content="" />
    <link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}">
{%endblock%}

{%block content%}
<div id="things_heading" class="col-xs-12">
	<h1>What they like</h1>
</div>

<div class="col-xs-12 generic_section" id="actors_section">
    <h2><i class="fa fa-star" aria-hidden="true"></i> Actors</h2>
    {% for obj in actor_list %}
        {%include 'things/snippets/actors.html'%}
    {%endfor%}

    {%if actor_list.count == 5%}
    <div class="col-xs-12 col-md-6">
        <a href="{%url 'things:actors'%}" class="generic_card_more">View all <i class="fa fa-hand-o-right" aria-hidden="true"></i></a>
    {%else%}
    <div class="col-xs-12">
        <p class="col-xs-12"><a href="{%url 'things:new_actor'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a> new to fill this section up.</p>
    {%endif%}
    </div>
</div>

<div class="col-xs-12 generic_section" id="books_section">
    <h2><i class="fa fa-book" aria-hidden="true"></i> Books</h2>
    {% for obj in book_list %}
        {%include 'things/snippets/books.html'%}
    {%endfor%}

    {%if book_list.count == 5%}
    <div class="col-xs-12 col-md-6">
        <a href="{%url 'things:books'%}" class="generic_card_more">View all <i class="fa fa-hand-o-right" aria-hidden="true"></i></a>
    {%else%}
    <div class="col-xs-12">
        <p class="col-xs-12"><a href="{%url 'things:new_book'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a> new to fill this section up.</p>
    {%endif%}
    </div>
</div>

<div class="col-xs-12 generic_section" id="musicians_section">
    <h2><i class="fa fa-music" aria-hidden="true"></i> Musicians</h2>
    {% for obj in musician_list %}
        {%include 'things/snippets/musicians.html'%}
    {%endfor%}

    
    {%if musician_list.count == 5%}
    <div class="col-xs-12 col-md-6">
        <a href="{%url 'things:musicians'%}" class="generic_card_more">View all <i class="fa fa-hand-o-right" aria-hidden="true"></i></a>
    {%else%}
    <div class="col-xs-12">
        <p class="col-xs-12"><a href="{%url 'things:new_musician'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a> new to fill this section up.</p>
    {%endif%}
    </div>
</div>

<div class="col-xs-12 generic_section" id="songs_section">
    <h2><i class="fa fa-heartbeat" aria-hidden="true"></i> Songs</h2>
    {% for obj in song_list %}
        {%include 'things/snippets/songs.html'%}
    {%endfor%}

    {%if song_list.count == 5%}
    <div class="col-xs-12 col-md-6">
        <a href="{%url 'things:songs'%}" class="generic_card_more">View all <i class="fa fa-hand-o-right" aria-hidden="true"></i></a>
    {%else%}
    <div class="col-xs-12">
        <p class="col-xs-12"><a href="{%url 'things:new_song'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a> new to fill this section up.</p>
    {%endif%}
    </div>
</div>

<div class="col-xs-12 generic_section" id="movies_section">
    <h2><i class="fa fa-film" aria-hidden="true"></i> Movies</h2>
    {% for obj in movie_list %}
        {%include 'things/snippets/movies.html'%}
    {%endfor%}

    
    {%if movie_list.count == 5%}
    <div class="col-xs-12 col-md-6">
        <a href="{%url 'things:movies'%}" class="generic_card_more">View all <i class="fa fa-hand-o-right" aria-hidden="true"></i></a>
    {%else%}
    <div class="col-xs-12">
        <p class="col-xs-12"><a href="{%url 'things:new_movie'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a> new to fill this section up.</p>
    {%endif%}
    </div>
</div>

<div class="col-xs-12 generic_section" id="tvshows_section">
    <h2><i class="fa fa-tv" aria-hidden="true"></i> TV Shows</h2>
    {% for obj in tvshow_list %}
        {%include 'things/snippets/tvshows.html'%}
    {%endfor%}

    
    {%if tvshow_list.count == 5%}
    <div class="col-xs-12 col-md-6">
        <a href="{%url 'things:tvshows'%}" class="generic_card_more">View all <i class="fa fa-hand-o-right" aria-hidden="true"></i></a>
    {%else%}
    <div class="col-xs-12">
        <p class="col-xs-12"><a href="{%url 'things:new_tvshow'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a> new to fill this section up.</p>
    {%endif%}
    </div>
</div>

<div class="col-xs-12 generic_section" id="animes_section">
    <h2><i class="fa fa-play-circle" aria-hidden="true"></i> Anime</h2>
    {% for obj in anime_list %}
        {%include 'things/snippets/animes.html'%}
    {%endfor%}

    
    {%if anime_list.count == 5%}
    <div class="col-xs-12 col-md-6">
        <a href="{%url 'things:animes'%}" class="generic_card_more">View all <i class="fa fa-hand-o-right" aria-hidden="true"></i></a>
    {%else%}
    <div class="col-xs-12">
        <p class="col-xs-12"><a href="{%url 'things:new_anime'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a> new to fill this section up.</p>
    {%endif%}
    </div>
</div>

<div class="col-xs-12 generic_section" id="vehicles_section">
    <h2><i class="fa fa-car" aria-hidden="true"></i> Vehicles</h2>
    {% for obj in vehicle_list %}
        {%include 'things/snippets/vehicles.html'%}
    {%endfor%}

    
    {%if vehicle_list.count == 5%}
    <div class="col-xs-12 col-md-6">
        <a href="{%url 'things:vehicles'%}" class="generic_card_more">View all <i class="fa fa-hand-o-right" aria-hidden="true"></i></a>
    {%else%}
    <div class="col-xs-12">
        <p class="col-xs-12"><a href="{%url 'things:new_vehicle'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create</a> new to fill this section up.</p>
    {%endif%}
    </div>
</div>

{%endblock content%}