things/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    url(r'^join/$', views.register, name='join'),
    url(r'^profile/(?P<slug>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^settings/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.SettingsUpdateView.as_view(), name='edit_settings'),

    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^user/(?P<user_slug>[\w-]+)/$', views.user_profile, name='user'),

    url(r'^actors/$', views.ActorListView.as_view(), name='actors'),
    url(r'^actors/(?P<slug>[\w-]+)/$', views.ActorListView.as_view(), name='search_actors'),
    url(r'^add-actor/$', views.ActorCreateView.as_view(),name='new_actor'),
    url(r'^actor/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.ActorUpdateView.as_view(), name='edit_actor'),
    url(r'^actor/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.ActorDeleteView.as_view(),name='del_actor'),
    url(r'^actor/(?P<slug>[\w-]+)/$', views.ActorDetailView.as_view(), name='actor'),

    url(r'^vehicles/$', views.VehicleListView.as_view(), name='vehicles'),
    url(r'^add-vehicle/$', views.VehicleCreateView.as_view(),name='new_vehicle'),
    url(r'^vehicle/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.VehicleUpdateView.as_view(), name='edit_vehicle'),
    url(r'^vehicle/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.VehicleDeleteView.as_view(),name='del_vehicle'),
    url(r'^vehicle/(?P<slug>[\w-]+)/$', views.VehicleDetailView.as_view(), name='vehicle'),

    url(r'^musicians/$', views.MusicianListView.as_view(), name='musicians'),
    url(r'^add-musician/$', views.MusicianCreateView.as_view(),name='new_musician'),
    url(r'^musician/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.MusicianUpdateView.as_view(), name='edit_musician'),
    url(r'^musician/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.MusicianDeleteView.as_view(),name='del_musician'),
    url(r'^musician/(?P<slug>[\w-]+)/$', views.MusicianDetailView.as_view(), name='musician'),

    url(r'^movies/$', views.MovieListView.as_view(), name='movies'),
    url(r'^add-movie/$', views.MovieCreateView.as_view(),name='new_movie'),
    url(r'^movie/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.MovieUpdateView.as_view(), name='edit_movie'),
    url(r'^movie/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.MovieDeleteView.as_view(),name='del_movie'),
    url(r'^movie/(?P<slug>[\w-]+)/$', views.MovieDetailView.as_view(), name='movie'),

    url(r'^tvshows/$', views.TVShowListView.as_view(), name='tvshows'),
    url(r'^add-tvshow/$', views.TVShowCreateView.as_view(),name='new_tvshow'),
    url(r'^tvshow/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.TVShowUpdateView.as_view(), name='edit_tvshow'),
    url(r'^tvshow/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.TVShowDeleteView.as_view(),name='del_tvshow'),
    url(r'^tvshow/(?P<slug>[\w-]+)/$', views.TVShowDetailView.as_view(), name='tvshow'),

    url(r'^animes/$', views.AnimeListView.as_view(), name='animes'),
    url(r'^add-anime/$', views.AnimeCreateView.as_view(),name='new_anime'),
    url(r'^anime/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.AnimeUpdateView.as_view(), name='edit_anime'),
    url(r'^anime/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.AnimeDeleteView.as_view(),name='del_anime'),
    url(r'^anime/(?P<slug>[\w-]+)/$', views.AnimeDetailView.as_view(), name='anime'),

    url(r'^songs/$', views.SongListView.as_view(), name='songs'),
    url(r'^add-song/$', views.SongCreateView.as_view(),name='new_song'),
    url(r'^song/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.SongUpdateView.as_view(), name='edit_song'),
    url(r'^song/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.SongDeleteView.as_view(),name='del_song'),
    url(r'^song/(?P<slug>[\w-]+)/$', views.SongDetailView.as_view(), name='song'),

    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^add-book/$', views.BookCreateView.as_view(),name='new_book'),
    url(r'^book/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.BookUpdateView.as_view(), name='edit_book'),
    url(r'^book/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.BookDeleteView.as_view(),name='del_book'),
    url(r'^book/(?P<slug>[\w-]+)/$', views.BookDetailView.as_view(), name='book'),
]

til/urls.py
from django.conf.urls import  include, url
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('things.urls', namespace="things")),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

things/models.py
import os

from django.db import models
from django.db.models import F
from django.db.models.signals import pre_save, post_save
from django.conf import settings
from django.contrib.auth.models import User as UserModel
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django_countries.fields import CountryField

from .utils import *

User = settings.AUTH_USER_MODEL

class Profile(models.Model):
    owner           =models.ForeignKey(User)
    first_name      =models.CharField(max_length=50, blank=True, null=True,validators=[alphanumspacedash])
    last_name       =models.CharField(max_length=50, blank=True, null=True, validators=[alphanumspacedash])
    dob             =models.DateField(blank=True, null=True)
    location        =models.CharField(null=True, blank=True, max_length = 50)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
        
    def __str__(self):
        return self.owner.username
    
    def get_absolute_url(self):
        return reverse('things:profile', kwargs={'slug':self.slug})

    def get_initials(self):
        initial =''
        if not (self.first_name and self.last_name):
            initial=self.owner.username[0]
        else:
            if self.first_name:
                initial+=self.first_name[0]
            if self.last_name:
                initial+=self.last_name[0]
        return initial

    class Meta:
        ordering = ('owner','timestamp',)

    @property
    def title(self):
        return self.owner.username

class Settings(models.Model):
    owner = models.ForeignKey(User)
    show_actors =models.BooleanField(default=False)
    show_directors =models.BooleanField(default=False)
    show_writers =models.BooleanField(default=False)
    show_artists =models.BooleanField(default=False)
    show_musicians =models.BooleanField(default=False)
    show_dancers =models.BooleanField(default=False)
    show_sportspersons =models.BooleanField(default=False)
    show_fitnesspersons =models.BooleanField(default=False)
    show_femalemodels =models.BooleanField(default=False)
    show_songs =models.BooleanField(default=False)
    show_movies =models.BooleanField(default=False)
    show_tvshows =models.BooleanField(default=False)
    show_animes =models.BooleanField(default=False)
    show_books =models.BooleanField(default=False)
    show_foods =models.BooleanField(default=False)
    show_youtubechannels =models.BooleanField(default=False)
    show_websites =models.BooleanField(default=False)
    show_apps =models.BooleanField(default=False)
    show_videogames =models.BooleanField(default=False)
    show_cars=models.BooleanField(default=False)
    show_bikes =models.BooleanField(default=False)
    show_adultmodels =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
        
    def __str__(self):
        return self.owner.username
    
    def get_absolute_url(self):
        return reverse('things:profile', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('owner','timestamp',)
        verbose_name_plural = "settings"

    @property
    def title(self):
        return self.owner.username


def user_registration_receiver(sender, instance, *args, **kwargs):
    if not Profile.objects.filter(owner=instance):
        newpro=Profile.objects.create(owner=instance)
        newpro.slug=instance.username
        newpro.save()
    if not Settings.objects.filter(owner=instance):
        newset=Settings.objects.create(owner=instance)
        newset.slug=instance.username
        newset.save()

post_save.connect(user_registration_receiver, sender=UserModel)

class Actor(models.Model):
    genders = (
		('f', 'Female'),
        ('m', 'Male'),
        ('o', 'Not Specified'),
    )
    def update_image_file(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (instance.slug, ext)
        return os.path.join('actors', filename)

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedash])
    gender          =models.CharField(choices=genders, blank=False, max_length=12, default='o')
    country         =CountryField(blank_label='(select country)')
    dob             =models.DateField(blank=False, default='01/01/89')
    image           =models.ImageField(upload_to=update_image_file, blank=True, null=True)
    insta           =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('things:actor', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name')
        unique_together = ('owner', 'rank', 'gender')

    @property
    def is_female(self):
        if self.gender == 'f':
            return True
        else:
            return False

    @property
    def title(self):
        return self.name


class Director(models.Model):    
    def update_image_file(instance, filename):
        pass

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedash])
    country         =CountryField(blank_label='(select country)')
    is_active	    =models.BooleanField(default=True)
    image_url        =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('things:director', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name',)
        unique_together = ('owner', 'rank')

    @property
    def title(self):
        return self.name


class Writer(models.Model):
    genders = (
		('f', 'Female'),
        ('m', 'Male'),
    )
    def update_image_file(instance, filename):
        pass

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedashq])
    gender          =models.CharField(choices=genders, blank=False, max_length=20)
    genres          =models.CharField(blank=False, max_length=80)
    languages       =models.CharField(blank=False, max_length=80)
    country         =CountryField(blank_label='(select country)')
    is_active	    =models.BooleanField(default=True)
    image_url        =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('things:writer', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name',)
        unique_together = ('owner', 'rank')

    @property
    def title(self):
        return self.name


class Artist(models.Model):
    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedashq])
    country         =CountryField(blank_label='(select country)')
    genres          =models.CharField(blank=False, max_length=80)
    is_active	    =models.BooleanField(default=True)
    image_url       =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('things:artist', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name',)
        unique_together = ('owner', 'rank')

    @property
    def title(self):
        return self.name


class Musician(models.Model):
    mtypes = (
		('fs', 'Female Singer'),
        ('ms', 'Male Singer'),
        ('bs', 'Band/Duo/Group'),
    )
    def update_image_file(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (instance.slug, ext)
        return os.path.join('musicians', filename)

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedashq])
    mtype           =models.CharField(choices=mtypes, blank=False, max_length=20)
    country         =CountryField(blank_label='(select country)')
    languages       =models.CharField(blank=False, max_length=80)

things/templates/things/snippets/actors.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
    <div class="col-xs-12 col-sm-6 generic_card_wrapper">
        <div class="generic_card">
            <div class="generic_card_text col-xs-8">
                <h2>
                    {{obj.name}}<i class="{{obj.country.flag_css }}"></i></h2>
                <div>
                    <p class="generic_card_info2">{{obj.get_gender_display}}</p>
                    <p class="generic_card_info1">{{obj.dob}}</p>
                    <p class="generic_creator">
                        Created by {{obj.owner}}
                    </p>
                </div>
            </div>
            <div class="generic_card_img col-xs-4">
                {%if request.user.is_authenticated%}
                    {%if request.user == obj.owner%}
                    <span class="generic_rank">
                        {%if obj.rank%}
                        <span class="glyphicon glyphicon-flash"></span> {{obj.get_rank_display}}
                        {%endif%}
                    </span>
                    {%endif%}
                {%endif%}
                <img src="{{obj.image.url}}" alt="{{obj.name}} image">
            </div>
        </div>
    </div>
</a>

things/templates/things/snippets/anime.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
    <div class="col-xs-12 col-sm-6 generic_card_wrapper">
        <div class="generic_card">
            <div class="generic_card_text col-xs-8">
                <h2>{{obj.name}}</h2>
                <div>
                    <p class="generic_card_info2">{{obj.get_anime_type_display}}</p>

                    <p class="generic_creator">
                        Created by {{obj.owner}}
                    </p>
                </div>
            </div>
            <div class="generic_card_img col-xs-4">
                {%if request.user.is_authenticated%}
                    {%if request.user == obj.owner%}
                    <span class="generic_rank">
                        {%if obj.rank%}
                            <span class="glyphicon glyphicon-flash"></span> {{obj.get_rank_display}}
                        {%endif%}
                    </span>
                    {%endif%}
                {%endif%}
                <img src="{{obj.poster}}" alt="{{obj.name}} poster">
            </div>
        </div>
    </div>
</a>

things/templates/things/snippets/animes.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
    <div class="col-xs-12 col-sm-6 generic_card_wrapper">
        <div class="generic_card">
            <div class="generic_card_text col-xs-8">
                <h2>{{obj.name}}</h2>
                <div>
                    <p class="generic_card_info2">{{obj.get_anime_type_display}}</p>

                    <p class="generic_creator">
                        Created by {{obj.owner}}
                    </p>
                </div>
            </div>
            <div class="generic_card_img col-xs-4">
                {%if request.user.is_authenticated%}
                    {%if request.user == obj.owner%}
                    <span class="generic_rank">
                        {%if obj.rank%}
                            <span class="glyphicon glyphicon-flash"></span> {{obj.get_rank_display}}
                        {%endif%}
                    </span>
                    {%endif%}
                {%endif%}
                <img src="{{obj.poster}}" alt="{{obj.name}} poster">
            </div>
        </div>
    </div>
</a>

things/templates/things/snippets/books.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
    <div class="col-xs-12 col-sm-6 generic_card_wrapper">
        <div class="generic_card">
            <div class="generic_card_text col-xs-8">
                <h2>{{obj.name}}</h2>
                <div>
                    <p class="generic_card_info2">{{obj.get_read_status_display}}</p>
                    <p class="generic_creator">
                        Created by {{obj.owner}}
                    </p>
                </div>
            </div>
            <div class="generic_card_img col-xs-4">
                {%if request.user.is_authenticated%}
                    {%if request.user == obj.owner%}
                    <span class="generic_rank">
                        {%if obj.rank%}
                            <span class="glyphicon glyphicon-flash"></span> {{obj.get_rank_display}}
                        {%endif%}
                    </span>
                    {%endif%}
                {%endif%}
                <img src="{{obj.cover}}" alt="{{obj.name}} poster">
            </div>
        </div>
    </div>
</a>

things/templates/things/snippets/movies.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
        <div class="col-xs-12 col-sm-6 generic_card_wrapper">
            <div class="generic_card">
                <div class="generic_card_text col-xs-8">
                    <h2>{{obj.name}}</h2>
                    <div>
                        <p class="generic_card_info1">
                        {%for g in obj.genre.all%}
                            <span class="generic_genre">{{g.name}}</span>
                        {%endfor%}
                        </p>
                        <p class="generic_card_info2">{{obj.year}}</p>
                        <p class="generic_creator">
                            Created by {{obj.owner}}
                        </p>
                    </div>
                </div>
                <div class="generic_card_img col-xs-4">
                    {%if request.user.is_authenticated%}
                        {%if request.user == obj.owner%}
                        <span class="generic_rank">
                            {%if obj.rank%}
                                <span class="glyphicon glyphicon-flash"></span> {{obj.get_rank_display}}
                            {%endif%}
                        </span>
                        {%endif%}
                    {%endif%}
                    <img src="{{obj.poster}}" alt="{{obj.name}} poster">
                </div>
            </div>
        </div>
    </a>

things/templates/things/snippets/musicians.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
        <div class="col-xs-12 col-sm-6 generic_card_wrapper">
            <div class="generic_card">
                <div class="generic_card_text col-xs-8">
                    <h2>
                        {{obj.name}}<i class="{{obj.country.flag_css }}"></i></h2>
                    <div>
                        <p class="generic_card_info2">{{obj.get_mtype_display}}</p>
                        <p class="generic_card_info1">{{obj.genres}}</p>
                        <p class="generic_creator">
                            Created by {{obj.owner}}
                        </p>
                    </div>
                </div>
                <div class="generic_card_img col-xs-4">
                    {%if request.user.is_authenticated%}
                        {%if request.user == obj.owner%}
                        <span class="generic_rank">
                            {%if obj.rank%}
                                <span class="glyphicon glyphicon-flash"></span> {{obj.get_rank_display}}
                            {%endif%}
                        </span>
                        {%endif%}
                    {%endif%}
                    <img src="{{obj.image.url}}" alt="{{obj.name}} image">
                </div>
            </div>
        </div>
    </a>

things/templates/things/snippets/songs.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
    <div class="col-xs-12 col-sm-6 generic_card_wrapper">
        <div class="generic_card">
            <div class="generic_card_text col-xs-8">
                <h2>{{obj.name}}</h2>
                <div>
                    <p class="generic_card_info2">{{obj.singer}}</p>
                    <p class="generic_creator">
                        Created by {{obj.owner}}
                    </p>
                </div>
            </div>
            <div class="generic_card_img col-xs-4">
                {%if request.user.is_authenticated%}
                    {%if request.user == obj.owner%}
                    <span class="generic_rank">
                        {%if obj.rank%}
                            <span class="glyphicon glyphicon-flash"></span> {{obj.get_rank_display}}
                        {%endif%}
                    </span>
                    {%endif%}
                {%endif%}
                <img src="{{obj.cover_url}}" alt="{{obj.name}} poster">
            </div>
        </div>
    </div>
</a>

things/templates/things/snippets/tv.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
        <div class="col-xs-12 col-sm-6 generic_card_wrapper">
            <div class="generic_card">
                <div class="generic_card_text col-xs-8">
                    <h2>{{obj.name}}</h2>
                    <div>
                        <p class="generic_card_info2">{{obj.get_genre_display}}</p>
                        <p class="generic_creator">
                            Created by {{obj.owner}}
                        </p>
                    </div>
                </div>
                <div class="generic_card_img col-xs-4">
                    {%if request.user.is_authenticated%}
                        {%if request.user == obj.owner%}
                        <span class="generic_rank">
                            {%if obj.rank%}
                                <span class="glyphicon glyphicon-flash"></span> {{obj.get_rank_display}}
                            {%endif%}
                        </span>
                        {%endif%}
                    {%endif%}
                    <img src="{{obj.poster}}" alt="{{obj.name}} poster">
                </div>
            </div>
        </div>
    </a>

things/templates/things/snippets/tvshows.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
        <div class="col-xs-12 col-sm-6 generic_card_wrapper">
            <div class="generic_card">
                <div class="generic_card_text col-xs-8">
                    <h2>{{obj.name}}</h2>
                    <div>
                        <p class="generic_card_info1">
                        {%for g in obj.genre.all%}
                            <span class="generic_genre">{{g.name}}</span>
                        {%endfor%}
                        </p>
                        <p class="generic_creator">
                            Created by {{obj.owner}}
                        </p>
                    </div>
                </div>
                <div class="generic_card_img col-xs-4">
                    {%if request.user.is_authenticated%}
                        {%if request.user == obj.owner%}
                        <span class="generic_rank">
                            {%if obj.rank%}
                                <span class="glyphicon glyphicon-flash"></span> {{obj.get_rank_display}}
                            {%endif%}
                        </span>
                        {%endif%}
                    {%endif%}
                    <img src="{{obj.poster}}" alt="{{obj.name}} poster">
                </div>
            </div>
        </div>
    </a>

things/templates/things/snippets/vehicles.html
<a class="generic_card_link" href={{obj.get_absolute_url}}>
    <div class="col-xs-12 col-sm-6 generic_card_wrapper">
        <div class="generic_card">
            <div class="generic_card_text col-xs-8">
                <h2>{{obj.name}}<i class="{{ obj.country.flag_css }}"></i></h2>
                <div>
                    <p class="generic_card_info2">{{obj.get_vehicle_type_display}}</p>
                    <p class="generic_card_info1">{{obj.company}}</p>
                    <p class="generic_creator">
                        Created by {{obj.owner}}
                    </p>
                </div>
            </div>
            <div class="generic_card_img col-xs-4">
                <img src="{%if obj.image_url%}{{obj.image_url}}{%endif%}" alt="{{obj.name}} image">
            </div>
        </div>
    </div>
</a>