things/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    url(r'^join/$', views.register, name='join'),
    url(r'^profile/(?P<slug>[\w-]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^settings/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.SettingsUpdateView.as_view(), name='edit_settings'),

    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^user/(?P<user_slug>[\w-]+)/$', views.user_profile, name='user'),

    url(r'^actors/$', views.ActorListView.as_view(), name='actors'),
    url(r'^actors/(?P<slug>[\w-]+)/$', views.ActorListView.as_view(), name='search_actors'),
    url(r'^add-actor/$', views.ActorCreateView.as_view(),name='new_actor'),
    url(r'^actor/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.ActorUpdateView.as_view(), name='edit_actor'),
    url(r'^actor/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.ActorDeleteView.as_view(),name='del_actor'),
    url(r'^actor/(?P<slug>[\w-]+)/$', views.ActorDetailView.as_view(), name='actor'),

    url(r'^vehicles/$', views.VehicleListView.as_view(), name='vehicles'),
    url(r'^add-vehicle/$', views.VehicleCreateView.as_view(),name='new_vehicle'),
    url(r'^vehicle/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.VehicleUpdateView.as_view(), name='edit_vehicle'),
    url(r'^vehicle/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.VehicleDeleteView.as_view(),name='del_vehicle'),
    url(r'^vehicle/(?P<slug>[\w-]+)/$', views.VehicleDetailView.as_view(), name='vehicle'),

    url(r'^musicians/$', views.MusicianListView.as_view(), name='musicians'),
    url(r'^add-musician/$', views.MusicianCreateView.as_view(),name='new_musician'),
    url(r'^musician/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.MusicianUpdateView.as_view(), name='edit_musician'),
    url(r'^musician/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.MusicianDeleteView.as_view(),name='del_musician'),
    url(r'^musician/(?P<slug>[\w-]+)/$', views.MusicianDetailView.as_view(), name='musician'),

    url(r'^movies/$', views.MovieListView.as_view(), name='movies'),
    url(r'^add-movie/$', views.MovieCreateView.as_view(),name='new_movie'),
    url(r'^movie/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.MovieUpdateView.as_view(), name='edit_movie'),
    url(r'^movie/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.MovieDeleteView.as_view(),name='del_movie'),
    url(r'^movie/(?P<slug>[\w-]+)/$', views.MovieDetailView.as_view(), name='movie'),

    url(r'^tvshows/$', views.TVShowListView.as_view(), name='tvshows'),
    url(r'^add-tvshow/$', views.TVShowCreateView.as_view(),name='new_tvshow'),
    url(r'^tvshow/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.TVShowUpdateView.as_view(), name='edit_tvshow'),
    url(r'^tvshow/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.TVShowDeleteView.as_view(),name='del_tvshow'),
    url(r'^tvshow/(?P<slug>[\w-]+)/$', views.TVShowDetailView.as_view(), name='tvshow'),

    url(r'^animes/$', views.AnimeListView.as_view(), name='animes'),
    url(r'^add-anime/$', views.AnimeCreateView.as_view(),name='new_anime'),
    url(r'^anime/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.AnimeUpdateView.as_view(), name='edit_anime'),
    url(r'^anime/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.AnimeDeleteView.as_view(),name='del_anime'),
    url(r'^anime/(?P<slug>[\w-]+)/$', views.AnimeDetailView.as_view(), name='anime'),

    url(r'^songs/$', views.SongListView.as_view(), name='songs'),
    url(r'^add-song/$', views.SongCreateView.as_view(),name='new_song'),
    url(r'^song/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.SongUpdateView.as_view(), name='edit_song'),
    url(r'^song/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.SongDeleteView.as_view(),name='del_song'),
    url(r'^song/(?P<slug>[\w-]+)/$', views.SongDetailView.as_view(), name='song'),

    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^add-book/$', views.BookCreateView.as_view(),name='new_book'),
    url(r'^book/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$', views.BookUpdateView.as_view(), name='edit_book'),
    url(r'^book/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$', views.BookDeleteView.as_view(),name='del_book'),
    url(r'^book/(?P<slug>[\w-]+)/$', views.BookDetailView.as_view(), name='book'),
]

til/urls.py
from django.conf.urls import  include, url
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('things.urls', namespace="things")),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

things/models.py
import os

from django.db import models
from django.db.models import F
from django.db.models.signals import pre_save, post_save
from django.conf import settings
from django.contrib.auth.models import User as UserModel
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django_countries.fields import CountryField

from .utils import *

User = settings.AUTH_USER_MODEL

class Profile(models.Model):
    owner           =models.ForeignKey(User)
    first_name      =models.CharField(max_length=50, blank=True, null=True,validators=[alphanumspacedash])
    last_name       =models.CharField(max_length=50, blank=True, null=True, validators=[alphanumspacedash])
    dob             =models.DateField(blank=True, null=True)
    location        =models.CharField(null=True, blank=True, max_length = 50)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
        
    def __str__(self):
        return self.owner.username
    
    def get_absolute_url(self):
        return reverse('things:profile', kwargs={'slug':self.slug})

    def get_initials(self):
        initial =''
        if not (self.first_name and self.last_name):
            initial=self.owner.username[0]
        else:
            if self.first_name:
                initial+=self.first_name[0]
            if self.last_name:
                initial+=self.last_name[0]
        return initial

    class Meta:
        ordering = ('owner','timestamp',)

    @property
    def title(self):
        return self.owner.username

class Settings(models.Model):
    owner = models.ForeignKey(User)
    show_actors =models.BooleanField(default=False)
    show_directors =models.BooleanField(default=False)
    show_writers =models.BooleanField(default=False)
    show_artists =models.BooleanField(default=False)
    show_musicians =models.BooleanField(default=False)
    show_dancers =models.BooleanField(default=False)
    show_sportspersons =models.BooleanField(default=False)
    show_fitnesspersons =models.BooleanField(default=False)
    show_femalemodels =models.BooleanField(default=False)
    show_songs =models.BooleanField(default=False)
    show_movies =models.BooleanField(default=False)
    show_tvshows =models.BooleanField(default=False)
    show_animes =models.BooleanField(default=False)
    show_books =models.BooleanField(default=False)
    show_foods =models.BooleanField(default=False)
    show_youtubechannels =models.BooleanField(default=False)
    show_websites =models.BooleanField(default=False)
    show_apps =models.BooleanField(default=False)
    show_videogames =models.BooleanField(default=False)
    show_cars=models.BooleanField(default=False)
    show_bikes =models.BooleanField(default=False)
    show_adultmodels =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
        
    def __str__(self):
        return self.owner.username
    
    def get_absolute_url(self):
        return reverse('things:profile', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('owner','timestamp',)
        verbose_name_plural = "settings"

    @property
    def title(self):
        return self.owner.username


def user_registration_receiver(sender, instance, *args, **kwargs):
    if not Profile.objects.filter(owner=instance):
        newpro=Profile.objects.create(owner=instance)
        newpro.slug=instance.username
        newpro.save()
    if not Settings.objects.filter(owner=instance):
        newset=Settings.objects.create(owner=instance)
        newset.slug=instance.username
        newset.save()

post_save.connect(user_registration_receiver, sender=UserModel)

class Actor(models.Model):
    genders = (
		('f', 'Female'),
        ('m', 'Male'),
        ('o', 'Not Specified'),
    )
    def update_image_file(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (instance.slug, ext)
        return os.path.join('actors', filename)

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedash])
    gender          =models.CharField(choices=genders, blank=False, max_length=12, default='o')
    country         =CountryField(blank_label='(select country)')
    dob             =models.DateField(blank=False, default='01/01/89')
    image           =models.ImageField(upload_to=update_image_file, blank=True, null=True)
    insta           =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('things:actor', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name')
        unique_together = ('owner', 'rank', 'gender')

    @property
    def is_female(self):
        if self.gender == 'f':
            return True
        else:
            return False

    @property
    def title(self):
        return self.name


class Director(models.Model):    
    def update_image_file(instance, filename):
        pass

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedash])
    country         =CountryField(blank_label='(select country)')
    is_active	    =models.BooleanField(default=True)
    image_url        =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('things:director', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name',)
        unique_together = ('owner', 'rank')

    @property
    def title(self):
        return self.name


class Writer(models.Model):
    genders = (
		('f', 'Female'),
        ('m', 'Male'),
    )
    def update_image_file(instance, filename):
        pass

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedashq])
    gender          =models.CharField(choices=genders, blank=False, max_length=20)
    genres          =models.CharField(blank=False, max_length=80)
    languages       =models.CharField(blank=False, max_length=80)
    country         =CountryField(blank_label='(select country)')
    is_active	    =models.BooleanField(default=True)
    image_url        =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('things:writer', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name',)
        unique_together = ('owner', 'rank')

    @property
    def title(self):
        return self.name


class Artist(models.Model):
    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedashq])
    country         =CountryField(blank_label='(select country)')
    genres          =models.CharField(blank=False, max_length=80)
    is_active	    =models.BooleanField(default=True)
    image_url       =models.URLField(max_length=200, blank=True, null=True)
    remarks         =models.TextField(blank=True, null=True)
    rank            =models.CharField(choices=top_five, blank=True, null=True, max_length=12)
    is_private      =models.BooleanField(default=False)
    slug            =models.SlugField(blank=True, null=True)
    timestamp       =models.DateTimeField(auto_now_add=True)
    updated         =models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('things:artist', kwargs={'slug':self.slug})

    class Meta:
        ordering = ('rank', 'name',)
        unique_together = ('owner', 'rank')

    @property
    def title(self):
        return self.name


class Musician(models.Model):
    mtypes = (
		('fs', 'Female Singer'),
        ('ms', 'Male Singer'),
        ('bs', 'Band/Duo/Group'),
    )
    def update_image_file(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (instance.slug, ext)
        return os.path.join('musicians', filename)

    owner           =models.ForeignKey(User)
    name            =models.CharField(max_length=50, blank=False, validators=[alphanumspacedashq])
    mtype           =models.CharField(choices=mtypes, blank=False, max_length=20)
    country         =CountryField(blank_label='(select country)')
    languages       =models.CharField(blank=False, max_length=80)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  
  <head>
    {%load static%}
    <!-- Global site tag (gtag.js) - Google Analytics -->

    <title>{% block title %}{% endblock %}LikeList</title>
    <link rel="icon" type="image/png" sizes="32x32" href="/media/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/media/favicon/favicon-16x16.png">
    <link rel="mask-icon" href="/media/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="apple-touch-icon" sizes="152x152" href="/media/favicon/apple-touch-icon.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- <meta name="theme-color" content="#250415"> -->

    <link rel="manifest" href="/media/favicon/site.webmanifest">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- SEO by Subham Sarangi -->
    {%block metatag%}{%endblock metatag%}
    <meta property="og:image:width" content="200">
    <meta property="og:image:height" content="200">
    <meta name="twitter:site" content="@likelist" />
    <meta name="twitter:card" content="summary_large_image" />
  
    <!-- <link rel="stylesheet" href="{% static 'styles/bootstrap.css' %}"> -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">  
    {%block loadcss%} {%endblock loadcss%}

    {% include 'css.html'%}
  </head>
  {% load static %}
  <body>
    {% include 'nav.html'%}
    <br>&nbsp;<br>
    <div class="pre-container">
      {%block precontent%}{%endblock precontent%}
    </div>    
    <div class="container">
      {%block content%} {%endblock content%}
    </div>
     <div class="post-container">
      {%block postcontent%}{%endblock postcontent%}
    </div>    
    {% include 'footer.html' %}

    <!-- <script src="{% static 'scripts/jquery.js' %}"></script>
    <script src="{% static 'scripts/bootstrap.js' %}"></script> -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {%block loadjs%} {%endblock loadjs%}

    {% include 'js.html'%}
  </body>
</html>

templates/footer.html
<footer>
    <p><i class="fa fa-copyright" aria-hidden="true"></i> 2019 All Rights Reserved</p>
    <p><i class="fa fa-code" aria-hidden="true"></i> with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="http://infogram.cf" target="_blank" rel="noopener noreferrer">Subham Sarangi</a></p>
    <h6><a target='_blank' href="/terms">Terms & Conditions</a>&nbsp;&nbsp;&nbsp;<a target='_blank' href="/privacy">Privacy Policy</a></h6>
</footer>

templates/js.html
<script>
// activating the datepicker
if((document.URL.split('/')[3]=='add-actor') || (document.URL.split('/')[3]=='actor' && document.URL.split('/')[6]=='edit')){
    $( ".datepicker" ).datepicker({
        changeMonth: true, 
        changeYear: true, 
        dateFormat: "dd/mm/yy",
        yearRange: "-90:+40",
        defaultDate: new Date(1989, 0, 01)
    });
}

// activating the chosen
if((document.URL.split('/')[3]=='add-movie') || (document.URL.split('/')[3]=='movie' && document.URL.split('/')[6]=='edit') || (document.URL.split('/')[3]=='add-tvshow') || (document.URL.split('/')[3]=='tvshow' && document.URL.split('/')[6]=='edit')){
    $('#id_genre').chosen({rtl: true});
    $('#id_genre_chosen').css('width','100%');
    $('#id_starring').chosen({rtl: true});
    $('#id_starring_chosen').css('width','100%');
}

// onclick filters in actors list page
if(document.URL.split('/')[3]=='actors'){
    $('#latest').click(function(){
        window.location.href='/actors/latest';
    });
    $('#oldest').click(function(){
        window.location.href='/actors/oldest';
    });
}

// selecting inputs with required & updating the DOM
var x =$('input,textarea,select').filter('[required]:visible');
for(i=0;i<x.length;i++){
    x[i].after("This field is required");
}

// adding a border in the update page
if(document.URL.split('/')[3]=='actor' && document.URL.split('/')[6]=='edit'){
    $('#id_image').parent().find('a').after('<img style="height:300px;object-fit:cover;    object-position: 0 -60px;" src="'+$('#id_image').parent().find('a').attr('href')+'">'); //from anchor href to a img src
    $('#id_image').parent().css({
        'border': '1px solid teal',
        'padding': '10px'
    });
    $('#image-clear_id+label').after('&nbsp;Or&nbsp;<br>');
}

// removing the 'likelist' from signin and signup navbars
if(document.URL.split('/')[3]=='login' || document.URL.split('/')[3]=='join'){
    $('.navbar-header').addClass('remove_this');
    $('.container').css('background', 'transparent');
}

// get the location button
$('#id_location').attr('readonly', true);
$('#id_location').after('<button type="button" id="get_location">Your Location</button>');
$('#get_location').click(function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition, showError);
  } else { 
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
});

function showPosition(position) {
  var pos = position.coords.latitude + 
  " " + position.coords.longitude;
  $('#id_location').val(pos);
  var html = '<a id="open_maps" target="_blank" href="https://www.google.com/maps/place/' + pos + '">Open Maps</a>';
  $('#get_location').after(html);
}

function showError(error) {
  switch(error.code) {
    case error.PERMISSION_DENIED:
      x.innerHTML = "User denied the request for Geolocation."
      break;
    case error.POSITION_UNAVAILABLE:
      x.innerHTML = "Location information is unavailable."
      break;
    case error.TIMEOUT:
      x.innerHTML = "The request to get user location timed out."
      break;
    case error.UNKNOWN_ERROR:
      x.innerHTML = "An unknown error occurred."
      break;
  }
}
</script>

templates/location.html
<script></script>

templates/nav.html
<nav>
    <div class="navbar navbar-fixed-top" style= "    box-shadow: 3px -2px 10px 1px #0000004f;">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#sitenav">
            <span class="icon-bar"></span>
            <span style="width: 27px;" class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand logo" href="/"><img src="/media/logo.png" width="64px;"></a>
      </div>
      <div class="navbar-collapse collapse" id="sitenav">
        <ul class="nav navbar-nav" style="padding-top: 8px;">
            <li class="dropdown" id="actors_dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Actors <i class="fa fa-angle-double-down" aria-hidden="true"></i></a>
                <ul class="dropdown-menu">              
                <li><a href="{%url 'things:new_actor'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create New</a></li>
                <li><a href="{%url 'things:actors'%}"><i class="fa fa-list" aria-hidden="true"></i> View List</a></li>
                </ul>
            </li>
            <li class="dropdown" id="musicians_dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Musicians <i class="fa fa-angle-double-down" aria-hidden="true"></i></a>
              <ul class="dropdown-menu">              
              <li><a href="{%url 'things:new_musician'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create New</a></li>
              <li><a href="{%url 'things:musicians'%}"><i class="fa fa-list" aria-hidden="true"></i> View List</a></li>
              </ul>
            </li>
            <li class="dropdown" id="songs_dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Songs <i class="fa fa-angle-double-down" aria-hidden="true"></i></a>
                <ul class="dropdown-menu">              
                <li><a href="{%url 'things:new_song'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create New</a></li>
                <li><a href="{%url 'things:songs'%}"><i class="fa fa-list" aria-hidden="true"></i> View List</a></li>
                </ul>
            </li>
            <li class="dropdown" id="books_dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Books <i class="fa fa-angle-double-down" aria-hidden="true"></i></a>
                <ul class="dropdown-menu">              
                <li><a href="{%url 'things:new_book'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create New</a></li>
                <li><a href="{%url 'things:books'%}"><i class="fa fa-list" aria-hidden="true"></i> View List</a></li>
                </ul>
            </li>
            <li class="dropdown" id="movies_dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Movies <i class="fa fa-angle-double-down" aria-hidden="true"></i></a>
                <ul class="dropdown-menu">              
                <li><a href="{%url 'things:new_movie'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create New</a></li>
                <li><a href="{%url 'things:movies'%}"><i class="fa fa-list" aria-hidden="true"></i> View List</a></li>
                </ul>
            </li>
            <li class="dropdown" id="tvshows_dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                TV <i class="fa fa-angle-double-down" aria-hidden="true"></i></a>
                <ul class="dropdown-menu">              
                <li><a href="{%url 'things:new_tvshow'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create New</a></li>
                <li><a href="{%url 'things:tvshows'%}"><i class="fa fa-list" aria-hidden="true"></i> View List</a></li>
                </ul>
            </li>
            <li class="dropdown" id="animes_dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Anime <i class="fa fa-angle-double-down" aria-hidden="true"></i></a>
                <ul class="dropdown-menu">              
                <li><a href="{%url 'things:new_anime'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create New</a></li>
                <li><a href="{%url 'things:animes'%}"><i class="fa fa-list" aria-hidden="true"></i> View List</a></li>
                </ul>
            </li>
            <li class="dropdown" id="vehicles_dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Vehicles <i class="fa fa-angle-double-down" aria-hidden="true"></i></a>
                <ul class="dropdown-menu">              
                <li><a href="{%url 'things:new_vehicle'%}"><i class="fa fa-plus" aria-hidden="true"></i> Create New</a></li>
                <li><a href="{%url 'things:vehicles'%}"><i class="fa fa-list" aria-hidden="true"></i> View List</a></li>
                </ul>
            </li>
        </ul>
  
        <ul class="nav navbar-nav navbar-right"> <!-- links for the logged in user -->
          {%if request.user.is_authenticated%}
            <li id="username">
                <a href="{%url 'things:profile' request.user %}"><i class="fa fa-user" aria-hidden="true"></i> {{request.user}}</a>
            </li>
            <li class="right" id="logout"><a href="/logout/"><small>Logout <i class="fa fa-sign-out" aria-hidden="true"></i></small></a></li>
          {%else%}
            <li id="auth"><p><a href="/login/">Login</a>&nbsp;<a href="/join/">Register</a></p></li>
          {%endif%}
        </ul>
      </div>
    </div>
  </nav>

templates/pagination2.html
{% if is_paginated %}
<div class="pagination col-xs-12">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt;previous</a>
        {% endif %}
        <span class="current">
            <strong>page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</strong>
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next&gt;&gt;</a>
        {% endif %}
    </span>
</div>
{% endif %}